In [1]:
import numpy as np
import math
import pandas as pd
from sklearn.naive_bayes import GaussianNB
import statistics as st

m1 = [0,0,0,0,0]
S1 =np.array([[0.8, 0.2, 0.1, 0.05, 0.01],
    [0.2, 0.7, 0.1, 0.03, 0.02],
    [0.1, 0.1, 0.8, 0.02, 0.01],
    [0.05, 0.03, 0.02, 0.9, 0.01],
    [0.01, 0.02, 0.01, 0.01, 0.8]])

a1 = np.random.multivariate_normal(m1, S1, 25) 
b1 = np.random.multivariate_normal(m1, S1, 5000)

In [2]:
m2=[1,1,1,1,1]
S2 =np.array([[0.9, 0.1, 0.05, 0.02, 0.01],
    [0.1, 0.8, 0.1, 0.02, 0.02],
    [0.05, 0.1, 0.7, 0.02, 0.01],
    [0.02, 0.02, 0.02, 0.6, 0.02],
    [0.01, 0.02, 0.01, 0.02, 0.7]])

a2 = np.random.multivariate_normal(m2, S2, 25)
b2 = np.random.multivariate_normal(m2, S2, 5000)

In [3]:
a=np.concatenate((a1,a2)) #50 points (X1) with class w1 & w2 for training 
training_class=np.concatenate(([0]*25,[1]*25)) #Training class labels

b=np.concatenate((b1,b2)) #10,000 points (X2) with class w1 & w1 for testing
test_class=np.concatenate(([0]*5000,[1]*5000)) #Class labels for testing

In [4]:
w1_v = st.mean(a1[0:25,0])
w1_w = st.mean(a1[0:25,1])
w1_x = st.mean(a1[0:25,2])
w1_y = st.mean(a1[0:25,3])
w1_z = st.mean(a1[0:25,4])

w2_v = st.mean(a2[0:25,0])
w2_w = st.mean(a2[0:25,1])
w2_x = st.mean(a2[0:25,2])
w2_y = st.mean(a2[0:25,3])
w2_z = st.mean(a2[0:25,4])

var1_v = st.variance(a1[0:25,0])
var1_w = st.variance(a1[0:25,1])
var1_x = st.variance(a1[0:25,2])
var1_y = st.variance(a1[0:25,3])
var1_z = st.variance(a1[0:25,4])

var2_v = st.variance(a2[0:25,0])
var2_w = st.variance(a2[0:25,1])
var2_x = st.variance(a2[0:25,2])
var2_y = st.variance(a2[0:25,3])
var2_z = st.variance(a2[0:25,4])

centroid = np.array([[w1_v,w1_w,w1_x, w1_y, w1_z],
                        [w2_v,w2_w,w2_x, w2_y,w2_z]])
variances = np.array([[var1_v,var1_w,var1_x,var1_y,var1_z],
                     [var2_v,var2_w,var2_x,var2_y,var2_z]])

print("Mean:")
print(centroid)
print("\nVariance:")
print(variances)

Mean:
[[ 0.02466538  0.02276334  0.07869002 -0.15902809  0.08030643]
 [ 0.58684045  0.7988728   1.00983985  1.03773726  0.78405446]]

Variance:
[[1.05960156 0.59883999 0.77011533 0.84560773 0.95168673]
 [0.91625302 0.88696589 0.60044618 0.58262541 0.87479258]]


In [5]:
def naive_bayes(mean,variance,test_point):

    attributes = len(mean)
    equation = 1
    for i in range(attributes):
        exponent =  math.exp(-((test_point[i] - mean[i]) ** 2 / (2 * variance[i])))
        k = (1 / (math.sqrt(2 * math.pi * variance[i])))
        equation = equation * exponent*k
       
    return equation

In [6]:

max_prob = 0
i=0
predicted_class = [0]*len(b)
true_class= test_class

for test_point in b :
        for j in range(0,2):

            probability = naive_bayes(centroid[j],variances[j],test_point)    
            if(max_prob < probability):
                max_prob = probability
                tag = j
                
        predicted_class[i] = tag;
        max_prob = 0    #reset
        i+=1
        
#print(predicted_class)    
        
#True Class vs Predicted Class display
x={'True_class': true_class, 'Predicted_class': predicted_class}
df=pd.DataFrame(x)
print(df)     

# No. of misclassifications      
count=0
for i in range(len(true_class)):
    if true_class[i]!=predicted_class[i]:
        count+=1
        


      True_class  Predicted_class
0              0                0
1              0                1
2              0                0
3              0                0
4              0                0
...          ...              ...
9995           1                1
9996           1                0
9997           1                0
9998           1                1
9999           1                1

[10000 rows x 2 columns]


In [7]:
print("Number of mislabeled points out of total %d points : %d" % 
      (b.shape[0],(test_class!=predicted_class).sum()))  #test_class=Y_test

#print(b.shape)
total = b.shape[0]
mislabeled_points = (test_class!=predicted_class).sum()
prob = mislabeled_points / total
    
print("\nError probability : ")    
print(prob)

Number of mislabeled points out of total 10000 points : 1309

Error probability : 
0.1309
